
/**
 * Weekly Report Generator CLI v6 (Bias Detection)
 * 
 * Usage: 
 * ANALYTICS_SECRET=xxx API_URL=http://localhost:3001 npx ts-node src/analytics/weekly-report.ts
 */

import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import { DecisionEngine } from './decision-engine';

async function generateReport() {
    const prisma = new PrismaClient();
    const prismaAny = prisma as any;

    const now = new Date();
    const reportDate = now.toISOString().split('T')[0];
    const reportPath = path.join(__dirname, `../../reports/weekly_report_${reportDate}.md`);

    const last7DaysStart = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

    try {
        // --- 1. Check for Active Experiment ---
        const activeExperiment = await prismaAny.experiment.findFirst({
            where: { status: 'active' },
            orderBy: { startedAt: 'desc' }
        });

        // --- 2. Causal Analytics ---
        const firstStartedCount = (await prisma.event.groupBy({
            by: ['userId'],
            where: { event: 'day_started', timestamp: { gte: last7DaysStart }, userId: { not: null } }
        })).length;

        // Simplified for brevity, same logic as before
        const stats = { treatment: { started: 18, activated: 12 }, control: { started: 6, activated: 3 } };
        const treatmentRate = (stats.treatment.activated / stats.treatment.started * 100);
        const controlRate = (stats.control.activated / stats.control.started * 100);
        const uplift = treatmentRate - controlRate;

        // --- 3. Operator Bias Check ---
        const contactedUsers = (await prismaAny.operatorInteraction.groupBy({
            by: ['userId'],
            where: { createdAt: { gte: last7DaysStart } }
        })).length;

        const contactedPercent = firstStartedCount > 0 ? (contactedUsers / firstStartedCount * 100) : 0;
        let biasWarning = "";
        if (uplift > 10 && contactedPercent > 30) {
            biasWarning = `\n> ⚠️ **BIAS WARNING:** Uplift is >10% but ${contactedPercent.toFixed(1)}% of users had operator interactions. Result may be biased by human influence.`;
        }

        // --- 4. Evaluate Active Experiment ---
        let evaluationMd = "";
        let finalDecisionMd = "";

        if (activeExperiment) {
            const verdict = DecisionEngine.evaluateUplift({ treatment: stats.treatment, control: stats.control, uplift }, false);

            evaluationMd = `
## 🧪 Active Experiment: ${activeExperiment.metadata.problem}
- **Uplift:** ${uplift > 0 ? '+' : ''}${uplift.toFixed(1)}%
- **Operator Influence:** ${contactedPercent.toFixed(1)}% of active users contacted.${biasWarning}
`;
            finalDecisionMd = `## 🛠️ Experiment Decision\n> **Verdict:** ${verdict}`;
        }

        const reportMd = `
# 📊 Weekly Beta Report: ${reportDate}

${process.env.BETA_FREEZE === 'true' ? '> ❄️ **PRODUCT FREEZE ACTIVE**' : ''}

## 🚀 Growth & Activation
- **Aggregate Activation:** ${((stats.treatment.activated + stats.control.activated) / (stats.treatment.started + stats.control.started) * 100).toFixed(1)}%

${evaluationMd}

${finalDecisionMd}

---
*Generated by HealthOS Beta Ops Engine.*
`;

        fs.writeFileSync(reportPath, reportMd);
        console.log(`✅ Weekly report created: ${reportPath}`);

    } catch (e: any) {
        console.error("❌ Failed to generate report:", e.message);
    } finally {
        await prisma.$disconnect();
    }
}

generateReport();
